language: python
python:
- '2.7'
install:
- pip install pytest
- python setup.py develop
script: py.test
sudo: false
env:
  global:
  - BUCKET=presslabstest
  - secure: l0yILppwTm4yLLeHZA3xQVa/rr7zsUQMil+1ms9MYMSofHezzlauvZEKBNWt0iSPa+a66BV5Eea8VE+yiGqcRzgaDg5+V5pxU7pTZ5XPgEdRn7Zjs8FMWKXUKWl/u/bUHAJqDWEQp9y/zfuH8THVuGvIkWLonH43dc5DIBa+Cmc4MGu8K8wxl8BE7OLq7nICprjJ1h6cpNroLx9+fko8KO+fcbt09X8yBxQTomXjY/LW/oFIeSL2lxgVn9S5LCOpB7iIb0PHJmizIwoZ7JBlu9ZK3+PSlbabxaj6qAD8imh2Mcs00wYonHkfcGmhBZ6JL17fzkDGizlTFgokYpkdF87SqFZR+9gMJsBJupdLQQWGmFOHauqbJ8V5VUTxZZqVUeMf1aaspvNuzryyAz22X+CrEm6qM6CQ7AAUxsiFvfgNjmTARjAwtsQay6FOK5BW3u2lGJD9sPW6njch6X7spG6i5aRFEUOJLwLI5eAvW0V8YGZFfxu3asUAKeQ3ZysXIBPY7RnOF2gA5rez0LaImCrp3iWTWogY6U9CUFs7V6Reb8rA1At2n2SDVG8LENqRoNImYrSEQdRowPiVWnFOOpJdqfj3RdjsPs6gc6XDPdt57eUO25CzsIXK0fzO9Rrd2Ia2YQS4Q8QDv72Dmkn5SKwwN2f+hi8lLBf+2i1j3pk=
  - secure: VzndU8t8iWLdXHDnmMyTpyXrzCOaqvbs9aMrOszRutp+V9p2PXeUxMLWihImrS/tY1ZHckCiZs8ZAbJdxc0z3z4zXeFXZNS0hXIjyXS5rmcwgpsS9PAe+soHrFjw/1JdEjQUupACIB/+E0ZSkq4YsgSjT7aS39/oJapnCehZ1Lk+ZTN/BHgLXVs7h4BQMBDNbySbKhSD5E6McJ+/xAu8R5MUnkpyd/HY7hWvHT9VosgQUafdg9ZbyStU8qh2V4xOQDNyKI8Qfad0v3DuOxxnPIFNFLYHd9dSuQhzJ3vILvoMgrYcTre+ftrcVqRr+gxvcN9GHc7PjYonNVEwt2cU6vEytC/+yVk7qVBX3u41rP3YZRm7aBP5age1zbBlcBpMVCuMZvmTwwQsZR/5LUOLm9SU7fYzRgSiRKnsnAms2NqXB1STC0fDZao4RzBhI94kQhyKPkWE9I99ShfZDqlLvOw8CuYPdMKwX+iCSm4J9YA66g8Dpw5nCHSOzzyXJLIUS23d0u7ZbWqGji5Ff7ZL7m49M/HZL/68S7LGfcQIwa30OfHOyJJze+OS+TSIZsXi3PPgoSy9UOJFwJJbWFHPiLCk2FQoryXNnaZuVdhdbxN5GTqaSOeW8+i6a/D+zlqUgWMmOYg2ctLwRtqVsd7+FdPGATG72aFAdkgV+6urUQ0=
